"""D4: recognition follows the scenario, not the vanilla 1836 Western club (user decision 25 Sep 2026).

- Every organised Islamic state is `recognized` (Egypt, Morocco, Tunis, Oman, Sokoto, Hijaz...).
- Europe, European-born colonies and settler states, and the Christian Caucasus kingdoms stay
  `recognized`.
- Every other organised non-Muslim state is `unrecognized`: the Chinese states, Manchuria and the
  Mongol khanates, the Hindu/Buddhist/Sikh states of India and Southeast Asia, the Volga and
  Siberian councils, and the native states of the Americas (Andes, Maya...).
Decentralized countries are unchanged. Technology tiers and laws are not recomputed: M1 derives
them from the frozen pre-M1b source, so a type change here does not move them.
Writes plan.yml (generated; review, do not hand-edit).
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
EUROPE_REGIONS = {"west_europe", "south_europe", "east_europe"}
# European Russia and the non-European-region states born of European or Christian settlement.
EUROPEAN_SPHERE = {
    "VPL", "UBD", "VNG", "VMS",                                  # Poland-Lithuania, Baltic, Novgorod, Muscovy
    "VGE", "VER",                                                # Christian Caucasus kingdoms
    "VDC", "VNH", "VVA", "VPA", "VNI", "VIN",                    # North Atlantic colonies and settler states
    "GBR", "VIT", "HAI", "VPI", "VLE", "VWI", "VNZ", "VBC", "VMB",  # Caribbean, isthmus, Plata, Mascarenes
}


def main() -> None:
    world = yaml.safe_load((ROOT / "world/scenario.yml").read_text())
    report = json.loads((ROOT / "build/world-political/active-political-report.json").read_text())
    index = json.loads((ROOT / "build/index.json").read_text())
    targets = yaml.safe_load((ROOT / "scenarios/atlas/mechanics_m1b_literacy/targets.yml").read_text())["countries"]
    plan = {}
    for tag in sorted(report["countries"]):
        current = world["countries"].get(tag, {}).get("country_type") or index["countries"].get(tag, {}).get("country_type")
        if current == "decentralized":
            continue
        goal = targets[tag]
        if goal["band"].startswith("islam"):
            wanted, reason = "recognized", "Islamic state"
        elif goal["region"] in EUROPE_REGIONS or tag in EUROPEAN_SPHERE:
            wanted, reason = "recognized", "European sphere"
        else:
            wanted, reason = "unrecognized", f"non-Muslim state ({goal['region']})"
        if wanted != current:
            plan[tag] = {"from": current, "to": wanted, "reason": reason,
                         "population": report["countries"][tag]["population"]}
    (HERE / "plan.yml").write_text(
        "# Generated by plan.py from the recognition rule; review, do not hand-edit.\n" +
        yaml.safe_dump({"version": 1, "countries": plan}, allow_unicode=True, sort_keys=True, width=110))
    up = [t for t, r in plan.items() if r["to"] == "recognized"]
    down = [t for t, r in plan.items() if r["to"] == "unrecognized"]
    print(f"recognized +{len(up)} ({sum(plan[t]['population'] for t in up):,} people); "
          f"unrecognized +{len(down)} ({sum(plan[t]['population'] for t in down):,} people)")
    print("to unrecognized:", " ".join(down))


if __name__ == "__main__":
    main()
