"""Write narrow mod overrides for vanilla files that error in the alternative 1836 world.

These vanilla files are outside Atlas' generated history folders and still name countries or
state owners that no longer exist. Each override is derived from the installed vanilla file
(read-only) and only removes entries whose scopes cannot resolve in the active world:

- history/trade, history/lobbies, history/treaties, history/production_methods: entries whose
  country or state owner is missing are dropped; valid entries are copied verbatim.
- history/military_deployments: 1836 war-front deployments (Texas, Mexico...) do not exist here;
  an empty container is written.
- journal_entries/02_peru_bolivia.txt: copied with `exists = c:BOL` guards on the two triggers
  evaluated every tick (396 opening-log errors).
- ve_andalusi culture: UTF-8 BOM and the six expected culture static modifiers + modifier types.
- scripted_effects/00_political_setup.txt: vanilla copy; effect_starting_politics_traditional skips
  serfdom when a school law is already active (Atlas writes explicit laws before inherited effects).

Run after `atlas build`; it reads the active report for landed countries and state owners.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
TOOLKIT = Path(os.environ.get("VIC3_TOOLS_HOME") or json.loads(
    (ROOT / ".vic3-tools.local.json").read_text())["toolkit"])
if sys.version_info < (3, 10):
    runtime = TOOLKIT / ".venv/bin/python"
    os.execv(str(runtime), [str(runtime), __file__, *sys.argv[1:]])
sys.path.insert(0, str(TOOLKIT / "src"))
os.chdir(ROOT)
from vic3 import pdx  # noqa: E402
from vic3.paths import VANILLA  # noqa: E402

NOTE = ("# The Golden Crescent override of vanilla {path}.\n"
        "# Generated by scenarios/runtime_cleanup/vanilla_overrides.py; do not hand-edit.\n"
        "# Entries naming countries or state owners absent from the 1836 alternative world are removed.\n")


def tags_in(node) -> set[str]:
    return set(re.findall(r"c:([A-Z0-9]{3})\b", pdx.dumps(node)))


def write(rel: str, text: str) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + text, encoding="utf-8")


def main() -> None:
    report = json.loads((ROOT / "build/world-political/active-political-report.json").read_text())
    landed = set(report["countries"])
    owners = {state: set(s["owners"]) for state, s in report["states"].items()}
    summary = {}

    # Trade: s:STATE = { region_state:TAG = { sg:goods = {...} } }
    rel = "common/history/trade/00_historical_trade.txt"
    root = pdx.parse_file(VANILLA / rel).get_node("TRADE")
    kept = pdx.Node([])
    for sb in root.items:
        state = sb.key[2:]
        inner = pdx.Node([ob for ob in sb.value.items if ob.key.split(":")[1] in owners.get(state, set())])
        if inner.items:
            kept.items.append(pdx.Item(sb.key, "=", inner))
    write(rel, NOTE.format(path=rel) + "TRADE = {\n" + pdx.dumps(kept) + "\n}\n")
    summary[rel] = (len(root.items), len(kept.items))

    # Lobbies and urban-center production methods: c:TAG ?= { ... } blocks
    for rel, key, child in (("common/history/lobbies/00_lobbies.txt", "LOBBIES", "create_political_lobby"),
                            ("common/history/production_methods/00_urban_center.txt", "PRODUCTION_METHODS", None)):
        root = pdx.parse_file(VANILLA / rel).get_node(key)
        kept = pdx.Node([])
        for cb in root.items:
            if cb.key[2:] not in landed:
                continue
            body = cb.value
            if child:
                body = pdx.Node([it for it in body.items if it.key != child or tags_in(it.value) <= landed])
                if not body.items:
                    continue
            kept.items.append(pdx.Item(cb.key, cb.op, body))
        write(rel, NOTE.format(path=rel) + f"{key} = {{\n" + pdx.dumps(kept) + "\n}\n")
        summary[rel] = (len(root.items), len(kept.items))

    # Treaties: create_treaty = { first_country second_country ... }
    rel = "common/history/treaties/00_historical_treaties.txt"
    root = pdx.parse_file(VANILLA / rel).get_node("TREATIES")
    kept = pdx.Node([it for it in root.items if tags_in(it.value) <= landed])
    write(rel, NOTE.format(path=rel) + "TREATIES = {\n" + pdx.dumps(kept) + "\n}\n")
    summary[rel] = (len(root.items), len(kept.items))

    rel = "common/history/military_deployments/00_military_deployments.txt"
    write(rel, NOTE.format(path=rel) + "# 1836 war-front deployments of the vanilla timeline do not exist here.\n"
                                        "MILITARY_DEPLOYMENTS = {\n}\n")
    summary[rel] = ("vanilla", 0)

    rel = "common/journal_entries/02_peru_bolivia.txt"
    text = (VANILLA / rel).read_text(encoding="utf-8-sig")
    guarded = text.replace("\tshould_be_involved = {\n\t\tOR = {\n\t\t\tc:BOL ?= this\n\t\t\tis_subject_of = c:BOL\n\t\t}\n\t}",
                           "\tshould_be_involved = {\n\t\texists = c:BOL\n\t\tOR = {\n\t\t\tc:BOL ?= this\n"
                           "\t\t\tis_subject_of = c:BOL\n\t\t}\n\t}", 1)
    guarded = guarded.replace("\tshould_show_when_not_involved = {\n",
                              "\tshould_show_when_not_involved = {\n\t\texists = c:BOL\n", 1)
    if guarded.count("exists = c:BOL") < text.count("exists = c:BOL") + 2:
        raise ValueError("vanilla 02_peru_bolivia.txt layout changed; update the guard patch")
    write(rel, "# The Golden Crescent override of vanilla " + rel + ": exists = c:BOL guards on the two\n"
               "# involvement triggers only (Bolivia does not exist in 1836 here). Generated by\n"
               "# scenarios/runtime_cleanup/vanilla_overrides.py; do not hand-edit.\n" + guarded)
    summary[rel] = ("guarded", 2)

    # Atlas writes a country's explicit laws before inherited effects, so the vanilla traditional
    # setup would re-impose serfdom on the M1b Islamic countries after their tenant-farmer and
    # schools laws (both school laws disallow serfdom). Serfdom is skipped only when a school law
    # is already active; every other country runs the vanilla effect unchanged.
    rel = "common/scripted_effects/00_political_setup.txt"
    text = (VANILLA / rel).read_text(encoding="utf-8-sig")
    block = text[text.index("effect_starting_politics_traditional = {"):]
    block = block[:block.index("\n}\n") + 3]
    old = "\telse = {\n\t\tactivate_law = law_type:law_monarchy\n\t\tactivate_law = law_type:law_land_based_taxation\n" \
          "\t\tactivate_law = law_type:law_mercantilism\n\t\tactivate_law = law_type:law_land_based_taxation\n" \
          "\t\tactivate_law = law_type:law_serfdom\n"
    new = old.replace("\t\tactivate_law = law_type:law_serfdom\n",
                      "\t\tif = {\n\t\t\tlimit = {\n\t\t\t\tNOT = { has_law = law_type:law_religious_schools }\n"
                      "\t\t\t\tNOT = { has_law = law_type:law_public_schools }\n\t\t\t}\n"
                      "\t\t\tactivate_law = law_type:law_serfdom\n\t\t}\n")
    if block.count(old) != 1:
        raise ValueError("vanilla effect_starting_politics_traditional layout changed; update the guard patch")
    write(rel, "# The Golden Crescent override of vanilla " + rel + ": effect_starting_politics_traditional\n"
               "# skips serfdom when a school law is already active (M1b). Generated by\n"
               "# scenarios/runtime_cleanup/vanilla_overrides.py; do not hand-edit.\n"
               + text.replace(block, block.replace(old, new), 1))
    summary[rel] = ("guarded", 1)

    culture = ROOT / "common/cultures/ve_andalusi.txt"
    body = culture.read_text(encoding="utf-8-sig")
    culture.write_text("﻿" + body, encoding="utf-8")
    modifiers, types = [], []
    for kind, typ, fmt in (("standard_of_living", "state_ve_andalusi_standard_of_living_add", "state"),
                           ("cultural_acceptance", "country_ve_andalusi_cultural_acceptance_add", "country"),
                           ("fervor_target", "country_fervor_target_ve_andalusi_add", "country")):
        for sign in ("positive", "negative"):
            modifiers.append(f"ve_andalusi_{kind}_modifier_{sign} = {{\n\ticon = \"gfx/interface/icons/timed_modifier_icons/"
                             f"modifier_flag_{sign}.dds\"\n\t{typ} = 1\n}}\n")
        types.append(f"{typ}={{\n\tdecimals=1\n\tcolor=good\n\tgame_data={{\n\t\tai_value=0\n\t}}\n}}\n")
    write("common/static_modifiers/ve_andalusi_culture_modifiers.txt",
          "# Culture static modifiers the engine expects for the mod's ve_andalusi culture (vanilla pattern:\n"
          "# 07_culture_standard_of_living, 10_culture_cultural_acceptance, 11_culture_fervor_target).\n" + "\n".join(modifiers))
    write("common/modifier_type_definitions/ve_andalusi_modifier_types.txt",
          "# Modifier types used by ve_andalusi culture static modifiers (vanilla per-culture pattern).\n" + "\n".join(types))
    for rel, (before, after) in summary.items():
        print(f"{rel}: {before} -> {after}")


if __name__ == "__main__":
    main()
