"""B1: turn targets.yml into per-country technology and law changes plus the fixes they force (plan.yml, generated).

For every organized country whose group (targets.yml) gives a technology set different from its current one:
- technology becomes `{mode: replace, tier, add}` (the group tier + add, plus the current extras when the group
  keeps them); prerequisites are closed here so the fixes below see the final set;
- a law whose unlocking technology is gone, or that another final law disallows, is replaced by the first valid
  law of its group's fallback list; Egypt gets its written H2 laws (law_overrides);
- an institution whose enabling law is gone is set to 0;
- a building whose unlocking technology is gone is removed; a production method that needs a missing
  technology or law falls back to the most advanced allowed method of its group listed before it;
- army units take the best type of their arm that the final technologies allow (the M4 rule), so
  mechanics_m4_military/plan.py reproduces them after activation.
Reads build/balance/b1-source.yml and b1-source-report.json (copies of the active world and report).
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
TOOLKIT = Path(os.environ.get("VIC3_TOOLS_HOME") or json.loads(
    (ROOT / ".vic3-tools.local.json").read_text())["toolkit"])
if sys.version_info < (3, 10):
    runtime = TOOLKIT / ".venv/bin/python"
    os.execv(str(runtime), [str(runtime), __file__, *sys.argv[1:]])
sys.path.insert(0, str(TOOLKIT / "src"))
os.chdir(ROOT)
from vic3 import mechanics, pdx  # noqa: E402

HEADER = "# Generated by scenarios/atlas/balance_b1_tech_laws/plan.py from targets.yml; do not hand-edit.\n"


def m4_arms():
    text = (HERE.parent / "mechanics_m4_military/plan.py").read_text()
    scope = {}
    for name in ("INFANTRY", "CAVALRY", "ARTILLERY"):
        start = text.index(f"{name} = [")
        end = text.index("]\n", start) + 1
        exec(text[start:end], scope)  # noqa: S102 - trusted mod source: two literal lists
    return [scope["INFANTRY"], scope["CAVALRY"], scope["ARTILLERY"]]


def closure(techs: set, data: dict) -> set:
    out, todo = set(), list(techs)
    while todo:
        t = todo.pop()
        if t in out:
            continue
        out.add(t)
        todo.extend(data["technologies"].get(t, {}).get("unlocking_technologies", []))
    return out


def lists(record: dict, key: str) -> list:
    node = pdx.parse(record.get("script", ""))
    return node.get_list(key)


def main() -> None:
    targets = yaml.safe_load((HERE / "targets.yml").read_text())
    world = yaml.safe_load((ROOT / "build/balance/b1-source.yml").read_text())
    report = json.loads((ROOT / "build/balance/b1-source-report.json").read_text())
    bands = yaml.safe_load((HERE.parent / "mechanics_m1b_literacy/targets.yml").read_text())["countries"]
    tiers = {int(k): set(v) for k, v in json.loads(
        (HERE.parent / "mechanics_m1_institutions/tier-techs.json").read_text()).items()}
    index = json.loads((ROOT / "build/index.json").read_text())
    data = mechanics.catalog()
    laws, pms, pmgs, buildings = data["laws"], data["production_methods"], data["production_method_groups"], data["buildings"]
    arms = m4_arms()
    kind = lambda t: world["countries"].get(t, {}).get("country_type") or index["countries"].get(t, {}).get("country_type")

    def law_ok(law: str, techs: set, final: set) -> bool:
        rec = laws[law]
        if not set(rec.get("unlocking_technologies", [])) <= techs:
            return False
        return not any(other in final for other in rec.get("disallowing_laws", []))

    special = ("unlocking_geographic_regions", "unlocking_principles", "unlocking_company_categories",
               "unlocking_religions", "unlocking_production_methods")

    def plain(pm: str) -> bool:
        """A fallback candidate: no region, principle, company, religion or method condition."""
        return not any(lists(pms.get(pm, {}), key) for key in special)

    def pm_ok(pm: str, techs: set, final: set) -> bool:
        rec = pms.get(pm, {})
        if not set(rec.get("unlocking_technologies", [])) <= techs:
            return False
        if any(law in final for law in rec.get("disallowing_laws", [])):
            return False
        need = lists(rec, "unlocking_laws")
        return not need or any(law in final for law in need)

    plan, industry, summary = {}, {}, {"countries": 0, "laws": 0, "institutions": 0, "buildings_removed": 0,
                                      "levels_removed": 0, "pms": 0, "units": 0}
    for tag, country in sorted(report["countries"].items()):
        if kind(tag) == "decentralized":
            continue
        group = targets["countries"].get(tag) or targets["bands"].get((bands.get(tag) or {}).get("band"))
        if not group:
            continue
        spec = targets["groups"][group]
        current = set(country["technologies"])
        base = tiers[spec["tier"]] | set(spec.get("add", []))
        extras = sorted(current - closure(base, data)) if spec.get("keep_extras") else []
        final = closure(base | set(extras), data)
        if final == current and tag not in targets["law_overrides"] and tag not in targets.get("institution_overrides", {}):
            continue
        row = {"group": group, "technology": {"mode": "replace", "tier": spec["tier"],
                                              **({"add": sorted((set(spec.get("add", [])) | set(extras)))}
                                                 if spec.get("add") or extras else {})},
               "technologies_before": len(current), "technologies_after": len(final)}
        # laws
        wlaws = world["countries"].get(tag, {}).get("laws") or {}
        values = list(wlaws.get("values", []))
        have = set(country["laws"])
        overrides = targets["law_overrides"].get(tag, [])
        for law in overrides:
            grp = laws[law]["group"]
            have = {x for x in have if laws.get(x, {}).get("group") != grp} | {law}
        changes = {}
        for law in sorted(have):
            if law not in laws or law_ok(law, final, have - {law}):
                continue
            grp = laws[law]["group"]
            options = [x for x in targets["law_fallbacks"].get(grp, []) if x != law]
            pick = next((x for x in options if law_ok(x, final, have - {law})), None)
            if not pick:
                raise SystemExit(f"{tag}: no valid fallback for {law} in {grp}")
            have = (have - {law}) | {pick}
            changes[law] = pick
        if overrides or changes:
            groups = {laws[x]["group"] for x in list(changes) + overrides}
            kept = [x for x in values if laws.get(x, {}).get("group") not in groups]
            row["laws"] = {"values": sorted(set(kept) | {x for x in have if laws[x]["group"] in groups})}
            row["law_changes"] = changes
            summary["laws"] += len(changes) + len(overrides)
        # institutions
        inst = dict(world["countries"].get(tag, {}).get("institutions") or {})
        dropped = {name: 0 for name, level in inst.items() if level and not any(
            laws.get(x, {}).get("institution") == name for x in have)}
        for law, pick in changes.items():  # an inherited institution loses the law that enabled it
            name = laws[law].get("institution")
            if name and not any(laws.get(x, {}).get("institution") == name for x in have):
                dropped[name] = 0
        extra = targets.get("institution_overrides", {}).get(tag, {})
        if dropped or extra:
            row["institutions"] = {**inst, **dropped, **extra}
            summary["institutions"] += len(dropped) + len(extra)
        # buildings and production methods
        for state, st in report["states"].items():
            share = st["owners"].get(tag)
            if not share:
                continue
            for b in share["buildings"]:
                need = set(buildings.get(b["type"], {}).get("unlocking_technologies", []))
                if need and not need <= final:
                    industry.setdefault(state, {}).setdefault(tag, {})[b["type"]] = 0
                    summary["buildings_removed"] += 1
                    summary["levels_removed"] += b["level"]
                    continue
                new = []
                for pm in b["production_methods"]:
                    # change only what B1 breaks: valid with the old technologies and laws, invalid with the new
                    if pm_ok(pm, final, have) or not pm_ok(pm, current, set(country["laws"])):
                        new.append(pm)
                        continue
                    group_pms = next((pmgs[g]["production_methods"] for g in buildings[b["type"]]["production_method_groups"]
                                      if pm in pmgs[g]["production_methods"]), [pm])
                    before = group_pms[:group_pms.index(pm)]
                    choice = next((x for x in reversed(before) if plain(x) and pm_ok(x, final, have)), None) or \
                        next((x for x in group_pms if plain(x) and pm_ok(x, final, have)), None)
                    if not choice:
                        raise SystemExit(f"{tag} {state} {b['type']}: no allowed method for {pm}")
                    new.append(choice)
                    summary["pms"] += 1
                if new != b["production_methods"]:
                    industry.setdefault(state, {}).setdefault(tag, {})[b["type"]] = {
                        "level": b["level"], "production_methods": new}
        # army units
        military = world["countries"].get(tag, {}).get("military")
        if military:
            remap = {}
            for f in military["formations"]:
                for u in f.get("units", []):
                    arm = next((a for a in arms if any(u["type"] == x for x, _ in a)), None)
                    best = next((x for x, t in arm if t is None or t in final), None) if arm else u["type"]
                    if best != u["type"]:
                        remap[u["type"]] = best
            if remap:
                row["unit_remap"] = remap
        plan[tag] = row
        summary["countries"] += 1
    for tag, row in plan.items():
        summary["units"] += len(row.get("unit_remap", {}))
    out = {"summary": summary, "countries": plan, "industry": industry}
    (HERE / "plan.yml").write_text(HEADER + yaml.safe_dump(out, allow_unicode=True, sort_keys=False, width=120))
    print(f"wrote plan.yml: {summary}")


if __name__ == "__main__":
    main()
