"""D3: write the 1836 starting treaties of plan.yml as a mod history file.

Output: common/history/treaties/tgc_scenario_treaties.txt (generated; do not hand-edit). Every
treaty is checked against the active Atlas report before writing:
- both parties are landed, organised (not decentralized) countries;
- every article's acting countries have `international_relations` (all articles used unlock with it);
- alliance / defensive pact partners are independent and not in a subject relation with each other;
- a guarantee's source and target are independent and the source is not the target's subject.
The vanilla leftovers named in `drop_vanilla` are filtered by scenarios/runtime_cleanup/vanilla_overrides.py.
Run after `atlas build` and the active report.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = ROOT / "common/history/treaties/tgc_scenario_treaties.txt"
MUTUAL = {"alliance", "defensive_pact"}
DIRECTED = {"guarantee_independence", "trade_privilege", "military_access", "transit_rights"}


def main() -> None:
    plan = yaml.safe_load((HERE / "plan.yml").read_text())
    report = json.loads((ROOT / "build/world-political/active-political-report.json").read_text())
    world = yaml.safe_load((ROOT / "world/scenario.yml").read_text())
    overlords = report["diplomacy"]["overlords"]
    errors, blocks = [], []

    def country_ok(tag, where):
        if tag not in report["countries"]:
            errors.append(f"{where}: {tag} is not landed")
            return False
        if world["countries"].get(tag, {}).get("country_type") == "decentralized":
            errors.append(f"{where}: {tag} is decentralized")
            return False
        if "international_relations" not in report["countries"][tag]["technologies"]:
            errors.append(f"{where}: {tag} lacks international_relations")
        return True

    for row in plan["treaties"]:
        first, second, where = row["first"], row["second"], f"{row['name']} {row['first']}-{row['second']}"
        for tag in (first, second):
            country_ok(tag, where)
        items = []
        for art in row["articles"]:
            kind = art["article"]
            if kind in MUTUAL:
                if first in overlords or second in overlords or overlords.get(first) == second or overlords.get(second) == first:
                    errors.append(f"{where}: {kind} partners must be independent")
                items.append(f"\t\t{{\n\t\t\tarticle = {kind}\n\t\t}}")
            elif kind in DIRECTED:
                src, dst = art["source"], art["target"]
                if {src, dst} != {first, second}:
                    errors.append(f"{where}: {kind} parties differ from the treaty parties")
                if kind == "guarantee_independence" and (src in overlords or dst in overlords):
                    errors.append(f"{where}: guarantee parties must be independent")
                items.append(f"\t\t{{\n\t\t\tarticle = {kind}\n\t\t\tsource_country = c:{src}\n\t\t\ttarget_country = c:{dst}\n\t\t}}")
            else:
                errors.append(f"{where}: unsupported article {kind}")
        if row["date"] > "1836.1.1" and row["date"].split(".")[0] >= "1836":
            errors.append(f"{where}: treaty starts after 1836")
        blocks.append(f"# {row['name']}\ncreate_treaty = {{\n\tfirst_country = c:{first}\n\tsecond_country = c:{second}\n"
                      f"\tis_draft = no\n\tentered_into_force_on = {row['date']}\n\tbinding_period = {{\n\t\tyears = {row['years']}\n\t}}\n"
                      "\tarticles_to_create = {\n" + "\n".join(items) + "\n\t}\n}")
    if errors:
        raise SystemExit("\n".join(errors))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("﻿# The Golden Crescent 1836 starting treaties (canon: docs/scenario/diplomasi.md).\n"
                   "# Generated by scenarios/atlas/diplomacy_d3_treaties/build.py from plan.yml; do not hand-edit.\n"
                   "TREATIES = {\n" + "\n".join(blocks) + "\n}\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(blocks)} treaties, "
          f"{sum(len(r['articles']) for r in plan['treaties'])} articles")


if __name__ == "__main__":
    main()
