"""B2/B3: rebuild production buildings, production methods and state buildings to targets.yml (plan.yml, generated).

Works on the B0 model of the active world (build/balance/b2-source-report.json) for every country of a
B1 group that has a VA target:
1. Advanced groups (tier-1 protagonists and the Islamic core) move their buildings to the advanced
   production methods (targets.yml `advanced_methods`), as vanilla's tier-1 Britain starts.
2. Value added is brought into target x (1 +- tolerance): production buildings are scaled down, or levels are
   added from the growth mix in the country's states (allowed crops, resource caps, shared arable land and
   the jobs ceiling respected).
3. Market closure: in each in-scope market, missing inputs are built up to `input_floor` supply/demand and
   consumer-goods gluts are cut to `consumer_ceiling`.
4. State buildings: railways, universities and construction sectors to their listed totals; government
   administration to the bureaucracy margin; every coastal in-scope country keeps a port. Then closure again.
The plan records only the building levels and methods that differ from the source report.
"""

from __future__ import annotations

import collections as C
import copy
import importlib.util
import json
import math
import os
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
TOOLKIT = Path(os.environ.get("VIC3_TOOLS_HOME") or json.loads(
    (ROOT / ".vic3-tools.local.json").read_text())["toolkit"])
if sys.version_info < (3, 10):
    runtime = TOOLKIT / ".venv/bin/python"
    os.execv(str(runtime), [str(runtime), __file__, *sys.argv[1:]])
sys.path.insert(0, str(TOOLKIT / "src"))
os.chdir(ROOT)
from vic3 import mechanics, pdx  # noqa: E402
from vic3.paths import VANILLA  # noqa: E402

spec = importlib.util.spec_from_file_location("b0", HERE.parent / "balance_b0_model/measure.py")
B0 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(B0)

HEADER = "# Generated by scenarios/atlas/balance_b2_economy/plan.py from targets.yml; do not hand-edit.\n"
STAPLES = ["building_wheat_farm", "building_rye_farm", "building_maize_farm", "building_millet_farm", "building_rice_farm"]
ARABLE_GROUPS = {"bg_agriculture", "bg_plantations", "bg_ranching"}
PROTECTED = {"building_government_administration", "building_university", "building_port", "building_trade_center",
             "building_construction_sector", "building_naval_administration", "building_naval_fortification",
             "building_barrack", "building_railway", "building_arms_industry", "building_artillery_foundry",
             "building_munition_plant", "building_shipyard"}
COASTAL_ONLY = {"building_fishing_wharf", "building_whaling_station", "building_port", "building_shipyard"}
SPECIAL = ("unlocking_geographic_regions", "unlocking_principles", "unlocking_company_categories",
           "unlocking_religions", "unlocking_production_methods")


class Planner:
    def __init__(self):
        self.t = yaml.safe_load((HERE / "targets.yml").read_text())
        self.b1 = yaml.safe_load((HERE.parent / "balance_b1_tech_laws/targets.yml").read_text())
        bands = yaml.safe_load((HERE.parent / "mechanics_m1b_literacy/targets.yml").read_text())["countries"]
        self.report = json.loads((ROOT / "build/balance/b2-source-report.json").read_text())
        self.world_src = yaml.safe_load((ROOT / "build/balance/b2-source.yml").read_text())
        self.index = json.loads((ROOT / "build/index.json").read_text())
        self.rules = B0.Rules()
        self.data = mechanics.catalog()
        self.arable_res = {}
        for path in sorted((VANILLA / "map_data/state_regions").glob("*.txt")):
            for name, n in pdx.parse_file(path).pairs():
                if isinstance(n, pdx.Node):
                    self.arable_res[name] = {x.strip('"') for x in n.get_list("arable_resources")}
        kind = lambda t: self.world_src["countries"].get(t, {}).get("country_type") or \
            self.index["countries"].get(t, {}).get("country_type")
        self.group = {}
        for tag in self.report["countries"]:
            g = self.b1["countries"].get(tag) or self.b1["bands"].get((bands.get(tag) or {}).get("band"))
            if g in self.t["va_per_head"] and kind(tag) != "decentralized":
                self.group[tag] = g
            elif self.t.get("closure_only") and kind(tag) != "decentralized":
                self.group[tag] = "rest"
        self.capital = {t: self.world_src["countries"].get(t, {}).get("capital") or
                        self.index["countries"].get(t, {}).get("capital") for t in self.report["countries"]}
        # the working world, in the B0 model shape
        self.W = {"name": "b2", "overlords": self.report["diplomacy"]["overlords"],
                  "military": B0.military_units(self.rules, ROOT / "common/history/military_formations"),
                  "countries": {t: {"population": c["population"], "technologies": c["technologies"],
                                    "laws": c["laws"], "wealth": None} for t, c in self.report["countries"].items()},
                  "states": {sid: {"owners": {t: {"population": o["population"],
                                                  "buildings": copy.deepcopy(o.get("buildings", []))}
                                              for t, o in st["owners"].items()}} for sid, st in self.report["states"].items()}}
        self.state_info = {sid: {"arable": st.get("arable_land", 0), "caps": st.get("resource_caps", {})}
                           for sid, st in self.report["states"].items()}
        self.log = C.Counter()
        self._allowed, self._level = {}, {}

    # ------------------------------------------------------------ rules helpers
    def ancestors(self, building: str) -> set:
        out, g = set(), self.rules.building.get(building, {}).get("group")
        while g and g not in out:
            out.add(g)
            n = self.rules.groups.get(g)
            g = n.get_str("parent_group") if n is not None else None
        return out

    def pm_allowed(self, pm: str, tag: str, plain=True) -> bool:
        key = (pm, tag, plain)
        if key not in self._allowed:
            self._allowed[key] = self._pm_allowed(pm, tag, plain)
        return self._allowed[key]

    def _pm_allowed(self, pm: str, tag: str, plain=True, never_ok=False) -> bool:
        rec = self.data["production_methods"].get(pm)
        if rec is None or (pm in self.t["never"] and not never_ok):
            return False
        c = self.W["countries"][tag]
        if not set(rec.get("unlocking_technologies", [])) <= set(c["technologies"]):
            return False
        if any(law in c["laws"] for law in rec.get("disallowing_laws", [])):
            return False
        node = pdx.parse(rec["script"])
        need = node.get_list("unlocking_laws")
        if need and not any(law in c["laws"] for law in need):
            return False
        return not plain or not any(node.get_list(k) for k in SPECIAL)

    def choose(self, building: str, tag: str, current: list | None = None) -> list:
        prefs = self.t["advanced_methods"] if self.group.get(tag) in self.t["advanced_groups"] else self.t["basic_methods"]
        out = []
        for g in self.rules.building[building]["pmgs"]:
            opts = self.rules.pmg.get(g, [])
            keep = [p for p in (current or []) if p in opts]
            pref = [p for p in prefs.get(g, []) if p in opts and self.pm_allowed(p, tag)]
            if pref and (current is None or self.group.get(tag) in self.t["advanced_groups"]):
                out.append(pref[0])
            elif keep and self.pm_allowed(keep[0], tag, plain=False):
                out.append(keep[0])
            else:
                allowed = [p for p in opts if self.pm_allowed(p, tag)] or \
                    [p for p in opts if self._pm_allowed(p, tag, never_ok=True)]  # the law forces it (slave trade)
                if allowed:
                    out.append(allowed[0])
        return out

    def per_level(self, pms: list) -> tuple[C.Counter, float, float]:
        key = tuple(pms)
        if key not in self._level:
            self._level[key] = self._per_level(pms)
        return self._level[key]

    def _per_level(self, pms: list) -> tuple[C.Counter, float, float]:
        io, jobs = C.Counter(), 0.0
        for p in pms:
            pm = self.rules.pm.get(p)
            if pm:
                io.update(pm["io"])
                jobs += sum(pm["jobs"].values())
        va = sum((1 if k == "output" else -1) * v * self.rules.price.get(g, 0) for (k, g), v in io.items())
        return io, va, jobs

    def main_output(self, pms: list) -> str | None:
        """The good of largest output value (a by-product such as a sheep ranch's fertilizer is not it)."""
        io = self.per_level(pms)[0]
        outs = {g: v * self.rules.price.get(g, 0) for (k, g), v in io.items() if k == "output" and v > 0}
        return max(outs, key=outs.get) if outs else None

    def building_ok(self, building: str, tag: str, sid: str) -> bool:
        rec = self.data["buildings"].get(building)
        if rec is None or not set(rec.get("unlocking_technologies", [])) <= set(self.W["countries"][tag]["technologies"]):
            return False
        if building in COASTAL_ONLY and sid not in self.rules.coastal:
            return False
        if self.ancestors(building) & ARABLE_GROUPS and building not in self.arable_res.get(sid, set()):
            return False
        caps = self.state_info[sid]["caps"]
        if building in {"building_iron_mine", "building_coal_mine", "building_lead_mine", "building_sulfur_mine",
                        "building_logging_camp", "building_fishing_wharf", "building_gold_mine"} and not caps.get(building):
            return False
        return True

    # ------------------------------------------------------------ world helpers
    def shares(self, tag: str):
        for sid, st in self.W["states"].items():
            o = st["owners"].get(tag)
            if o is not None:
                yield sid, o

    def find(self, share: dict, building: str):
        return next((b for b in share["buildings"] if b["type"] == building), None)

    def jobs(self, share: dict) -> float:
        return sum(b["level"] * self.per_level(b["production_methods"])[2] for b in share["buildings"])

    def room(self, sid: str, building: str) -> int:
        """Levels of building the state can still take (shared arable land and resource caps)."""
        st, info = self.W["states"][sid], self.state_info[sid]
        free = 10 ** 6
        if self.ancestors(building) & ARABLE_GROUPS:
            used = sum(b["level"] for o in st["owners"].values() for b in o["buildings"]
                       if self.ancestors(b["type"]) & ARABLE_GROUPS)
            free = min(free, info["arable"] - used)
        cap = info["caps"].get(building)
        if cap is not None:
            used = sum(b["level"] for o in st["owners"].values() for b in o["buildings"] if b["type"] == building)
            free = min(free, cap - used)
        return free

    def infra(self, sid: str, tag: str, share: dict, extra: list | None = None, safe: bool = False) -> tuple[float, float]:
        """Modelled (supply, usage); `safe` leaves out the market-capital bonus the engine may apply differently."""
        if not hasattr(self, "_market"):
            self._market = self.market_of()
        cap = self.capital.get(tag)
        return B0.infra(self.rules, sid, set(self.W["countries"][tag]["technologies"]), share["population"],
                        share["buildings"] + (extra or []), cap == sid,
                        not safe and cap == sid and self._market.get(tag, tag) == tag)

    def staple(self, sid: str, share: dict) -> str | None:
        allowed = [s for s in STAPLES if s in self.arable_res.get(sid, set())]
        have = [b["type"] for b in share["buildings"] if b["type"] in allowed]
        return (have or allowed or [None])[0]

    def add_level(self, tag: str, building: str, n: int = 1, sid_pref: list | None = None) -> int:
        """Add up to n levels of building to the tag's best states; returns the levels placed."""
        placed = 0
        states = list(self.shares(tag))
        if sid_pref:
            order = {s: i for i, s in enumerate(sid_pref)}
            states.sort(key=lambda x: order.get(x[0], 99))
        for _ in range(n):
            best, best_score = None, None
            for sid, share in states:
                b = building if building != "staple" else self.staple(sid, share)
                if not b or not self.building_ok(b, tag, sid) or self.room(sid, b) <= 0:
                    continue
                pms = (self.find(share, b) or {}).get("production_methods") or self.choose(b, tag)
                if self.jobs(share) + self.per_level(pms)[2] > self.t["max_jobs_share"] * share["population"]:
                    continue
                supply, usage = self.infra(sid, tag, share, [{"type": b, "level": 1, "production_methods": pms}])
                if usage > supply and b not in ("building_port", "building_railway"):
                    continue
                score = share["population"] - self.jobs(share) / self.t["max_jobs_share"]
                if sid_pref:
                    score = -order.get(sid, 99) if sid in order else score - 1e12
                if best_score is None or score > best_score:
                    best, best_score = (sid, share, b, pms), score
            if not best:
                break
            sid, share, b, pms = best
            cur = self.find(share, b)
            if cur:
                cur["level"] += 1
            else:
                share["buildings"].append({"type": b, "level": 1, "production_methods": pms})
            placed += 1
        return placed

    def total(self, tag: str, building: str) -> int:
        return sum(b["level"] for _, share in self.shares(tag) for b in share["buildings"] if b["type"] == building)

    def cuttable(self, tag: str, building: str, n: int = 1) -> int:
        """Levels of building that may be cut without going below the canon minimum."""
        floor = self.t["canon_minimum"].get(tag, {}).get(building)
        return n if floor is None else max(0, min(n, self.total(tag, building) - floor))

    def ensure_canon(self):
        for tag, rows in self.t["canon_minimum"].items():
            if tag not in self.group:
                continue
            for building, floor in rows.items():
                for _ in range(200):
                    if self.total(tag, building) >= floor:
                        break
                    if self.add_level(tag, building):
                        self.log["canon_added"] += 1
                        continue
                    # no room: free it by removing the least valuable non-canon level (per infrastructure point)
                    rows_ = [(self.per_level(b["production_methods"])[1] / max(self.usage_of(b["type"]), 0.1), sid, share, b)
                             for sid, share in self.shares(tag) for b in share["buildings"]
                             if b["type"] not in PROTECTED and b["type"] not in rows and b["level"] > 0
                             and self.building_ok(building, tag, sid)]
                    if not rows_:
                        break
                    _, sid, share, b = min(rows_, key=lambda r: r[0])
                    b["level"] -= 1
                    share["buildings"] = [x for x in share["buildings"] if x["level"] > 0]
                    self.log["canon_room"] += 1

    def va(self, tag: str) -> float:
        total = 0.0
        for sid, share in self.shares(tag):
            for b in share["buildings"]:
                grp = self.rules.building.get(b["type"], {}).get("group")
                eos = 1 + min(max(b["level"] - 1, 0), 20) * 0.01 if self.rules.group_attr(grp, "economy_of_scale") == "yes" else 1
                total += self.per_level(b["production_methods"])[1] * b["level"] * eos
        return total

    def target(self, tag: str) -> float:
        per_head = self.t["va_per_head"].get(self.group[tag])
        return per_head * self.W["countries"][tag]["population"] / 1000 if per_head else self.va(tag)

    # ------------------------------------------------------------ steps
    def upgrade_methods(self):
        for tag, g in self.group.items():
            if g not in self.t["advanced_groups"]:
                continue
            for sid, share in self.shares(tag):
                for b in share["buildings"]:
                    new = self.choose(b["type"], tag, b["production_methods"])
                    if new != b["production_methods"]:
                        b["production_methods"] = new
                        self.log["methods_upgraded"] += b["level"]

    def fit_value_added(self):
        leader = self.t["rank_leader"]
        order = [leader] + sorted(t for t in self.group if t != leader and self.group[t] in self.t["va_per_head"])
        for tag in order:
            target, tol = self.target(tag), self.t["tolerance"]
            upper = target * (1 + tol)
            if tag != leader:
                upper = min(upper, self.t["rank_cap"] * self.va(leader))
            for _ in range(6):
                cur = self.va(tag)
                if cur <= upper or cur <= 0:
                    break
                f = min(target, upper) / cur
                for sid, share in self.shares(tag):
                    for b in share["buildings"]:
                        if b["type"] in PROTECTED or self.rules.building.get(b["type"], {}).get("group") == "bg_monuments":
                            continue
                        new = int(math.floor(b["level"] * f + 0.5))
                        cut = min(b["level"] - new, self.cuttable(tag, b["type"], b["level"] - new))
                        self.log["levels_cut"] += cut
                        b["level"] -= cut
                    share["buildings"] = [b for b in share["buildings"] if b["level"] > 0]
            favoured = tag in self.t["protagonists"] or tag in self.t.get("floor_countries", [])
            floor = self.t["protagonist_floor"] if favoured else 1 - tol
            if self.va(tag) < target * floor and self.W["countries"][tag]["population"] >= self.t["min_population"]:
                mix = self.t["mixes"][self.t["country_mix"].get(tag) or self.t["country_mix"].get(self.group[tag]) or "default"]
                added, dead = C.Counter(), set()
                while self.va(tag) < min(target, upper) and len(dead) < len(mix):
                    b = max((x for x in mix if x not in dead), key=lambda x: mix[x] / (added[x] + 1))
                    if self.add_level(tag, b):
                        added[b] += 1
                        self.log["levels_added"] += 1
                    else:
                        dead.add(b)
                if favoured and self.va(tag) < target * floor:
                    self.swap_for_value(tag, target * floor, mix)

    def fit_infrastructure(self):
        """Usage must stay within `infra_headroom` of the modelled supply. Short shares get railways when the owner
        has the technology, then ports when coastal (up to `max_ports_per_state`), then lose the levels with the
        least value added per infrastructure point."""
        head = self.t.get("infra_headroom", 1.0)
        for tag in sorted(self.group):
            for sid, share in self.shares(tag):
                supply, usage = self.infra(sid, tag, share, safe=True)
                if usage <= head * supply:
                    continue
                for building, cap in (("building_railway", 10 ** 6), ("building_port", self.t["max_ports_per_state"])):
                    if not self.building_ok(building, tag, sid):
                        continue
                    pms = self.choose(building, tag)
                    if building == "building_port" and "pm_basic_port" in self.rules.pmg.get("pmg_base_building_port", []):
                        pms = ["pm_basic_port"]
                    while usage > head * supply and (self.find(share, building) or {"level": 0})["level"] < cap:
                        cur = self.find(share, building)
                        if cur:
                            cur["level"] += 1
                            if building == "building_port":
                                cur["production_methods"] = pms
                        else:
                            share["buildings"].append({"type": building, "level": 1, "production_methods": pms})
                        self.log["infra_" + building[9:]] += 1
                        supply, usage = self.infra(sid, tag, share, safe=True)
                while usage > head * supply:
                    rows = []
                    for b in share["buildings"]:
                        if b["type"] in PROTECTED or b["level"] <= 0 or not self.cuttable(tag, b["type"]):
                            continue
                        use = self.usage_of(b["type"])
                        if use > 0:
                            rows.append((self.per_level(b["production_methods"])[1] / use, b))
                    if not rows:
                        break
                    b = min(rows, key=lambda r: r[0])[1]
                    b["level"] -= 1
                    self.log["infra_cut"] += 1
                    share["buildings"] = [x for x in share["buildings"] if x["level"] > 0]
                    supply, usage = self.infra(sid, tag, share, safe=True)

    def connect_isolated(self):
        """A share not connected by land to its market capital or to a port of its market cannot trade
        (concept_isolated_state): coastal ones get a port."""
        catalog = json.loads((ROOT / "build/world-political/world-baseline-catalog.json").read_text())
        neighbors = {s["id"]: set(s["neighbors"]) for s in catalog["states"]}
        market = self.market_of()
        states, ports = C.defaultdict(set), C.defaultdict(set)
        for sid, st in self.W["states"].items():
            for tag, share in st["owners"].items():
                states[market.get(tag, tag)].add(sid)
                if self.find(share, "building_port"):
                    ports[market.get(tag, tag)].add(sid)
        for m, owned in states.items():
            left = set(owned)
            while left:
                start = left.pop()
                comp, todo = {start}, [start]
                while todo:
                    for n in neighbors.get(todo.pop(), ()):
                        if n in left:
                            left.discard(n)
                            comp.add(n)
                            todo.append(n)
                if self.capital.get(m) in comp or comp & ports[m]:
                    continue
                for sid in sorted(comp, key=lambda s: -sum(o["population"] for o in self.W["states"][s]["owners"].values())):
                    placed = False
                    for tag, share in self.W["states"][sid]["owners"].items():
                        jobs = self.jobs(share) + self.per_level(["pm_basic_port"])[2]
                        if tag in self.group and market.get(tag, tag) == m and self.building_ok("building_port", tag, sid) \
                                and jobs <= self.t["max_jobs_share"] * share["population"]:
                            share["buildings"].append({"type": "building_port", "level": 1, "production_methods": ["pm_basic_port"]})
                            self.log["isolated_ports"] += 1
                            placed = True
                            break
                    if placed:
                        break
                else:
                    self.log["isolated_unfixable"] += 1

    def naval_administration(self):
        """Naval administration levels cover the fleets' crews (M4 plan) x naval_margin in their home states;
        levels above naval_excess x need are cut back to the margin."""
        m4 = yaml.safe_load((HERE.parent / "mechanics_m4_military/plan.yml").read_text())["countries"]
        for tag, row in sorted(m4.items()):
            if tag not in self.group:
                continue
            crew, homes = 0, C.Counter()
            for f in row["formations"]:
                for ship in f.get("ships", []):
                    crew += self.t["naval_crew"].get(ship["type"], 500) * ship["count"]
                    homes[ship["state"]] += ship["count"]
            need = math.ceil(crew * self.t["naval_margin"] / self.t["sailors_per_level"])
            shares = dict(self.shares(tag))
            have = self.total(tag, "building_naval_administration")
            if need and have > self.t["naval_excess"] * need:
                self.set_total(tag, "building_naval_administration", need)
                self.log["naval_admin_cut"] += have - need
                continue
            order = [s for s, _ in homes.most_common() if s in shares] + \
                    sorted((s for s in shares if s in self.rules.coastal and s not in homes), key=lambda s: -shares[s]["population"])
            order = [s for s in order if self.building_ok("building_naval_administration", tag, s)]
            if need > have and not order:
                self.log["naval_admin_unplaceable"] += 1
                continue
            i = 0
            while have < need:
                sid = order[i % len(order)] if i < len(order) * 3 else order[0]
                share = shares[sid]
                b = self.find(share, "building_naval_administration")
                if b:
                    b["level"] += 1
                else:
                    share["buildings"].append({"type": "building_naval_administration", "level": 1,
                                               "production_methods": self.choose("building_naval_administration", tag)})
                have += 1
                i += 1
                self.log["naval_admin_added"] += 1

    def make_room(self, tag: str, building: str, goods: dict) -> bool:
        """Infrastructure full: remove one level, of lowest value per infrastructure point, of a building whose main
        product the market has in surplus (supply/demand above 1.1), in a state that can take `building`."""
        best = None
        if tag in self.t["protagonists"] or tag in self.t.get("floor_countries", []):
            return False  # their infrastructure carries export industry; their gaps are imported
        for sid, share in self.shares(tag):
            b = building if building != "staple" else self.staple(sid, share)
            if not b or not self.building_ok(b, tag, sid) or self.room(sid, b) <= 0:
                continue
            for x in share["buildings"]:
                if x["type"] in PROTECTED or x["type"] == b or x["level"] <= 0 or not self.cuttable(tag, x["type"]):
                    continue
                g = self.main_output(x["production_methods"])
                row = goods.get(g) if g else None
                if not row:
                    continue
                demand = row["industry"] + row["military"] + row["pops"]
                if demand <= 0 or row["supply"] <= 1.1 * demand or self.usage_of(x["type"]) <= 0:
                    continue
                ratio = self.per_level(x["production_methods"])[1] / self.usage_of(x["type"])
                if best is None or ratio < best[0]:
                    best = (ratio, share, x)
        if not best:
            return False
        _, share, x = best
        x["level"] -= 1
        share["buildings"] = [y for y in share["buildings"] if y["level"] > 0]
        self.log["room_made"] += 1
        return True

    def close_world(self):
        """The input shortfall in-scope markets could not close themselves is added in exporter countries, largest
        first, while they stay under their VA ceiling."""
        market = self.market_of()
        exporters = sorted((t for t, g in self.group.items() if g in self.t["exporter_groups"]),
                           key=lambda t: -self.W["countries"][t]["population"])
        res = B0.measure(self.W, self.rules)
        unmet = C.Counter()
        for m, mk in res["markets"].items():
            if not any(market.get(t) == m for t in self.group):
                continue
            for g, x in mk["goods"].items():
                if g in self.t["producers"] and g not in self.t["consumer_goods"]:
                    demand = x["industry"] + x["military"] + x["pops"]
                    floor = self.t["input_floor_by_good"].get(g, self.t["input_floor"])
                    unmet[g] += max(0.0, floor * demand - x["supply"])
        for g, need in unmet.most_common():
            for tag in exporters:
                ceiling = self.target(tag) * (1 + self.t["tolerance"])
                for b in self.t["producers"][g]:
                    while need > 0 and self.va(tag) < ceiling:
                        probe = b if b != "staple" else "building_wheat_farm"
                        out = self.per_level(self.choose(probe, tag))[0][("output", g)]
                        if out < self.t.get("min_output_per_level", {}).get(g, 1e-9) or need < 0.5 * out \
                                or not self.add_level(tag, b):
                            break
                        need -= out
                        self.log[f"world_{g}"] += 1

    def usage_of(self, building: str) -> float:
        grp = self.rules.building.get(building, {}).get("group")
        return float(self.rules.group_attr(grp, "infrastructure_usage_per_level") or 0)

    def swap_for_value(self, tag: str, goal: float, mix: dict):
        """Infrastructure-bound protagonist: replace its lowest value-per-infrastructure levels with the mix
        building of the highest value per infrastructure point that the state can take."""
        swapped = C.Counter()
        for _ in range(3000):
            if self.va(tag) >= goal:
                return
            best = None
            for sid, share in self.shares(tag):
                low = [(self.per_level(b["production_methods"])[1] / self.usage_of(b["type"]), b) for b in share["buildings"]
                       if b["type"] not in PROTECTED and self.usage_of(b["type"]) > 0 and b["level"] > 0
                       and self.cuttable(tag, b["type"])]
                if not low:
                    continue
                low_ratio, low_b = min(low, key=lambda r: r[0])
                for cand in mix:
                    c = cand if cand != "staple" else self.staple(sid, share)
                    if not c or c == low_b["type"] or not self.building_ok(c, tag, sid) or self.usage_of(c) <= 0:
                        continue
                    arable_swap = self.ancestors(low_b["type"]) & ARABLE_GROUPS and self.ancestors(c) & ARABLE_GROUPS
                    if self.room(sid, c) <= 0 and not arable_swap:
                        continue
                    pms = (self.find(share, c) or {}).get("production_methods") or self.choose(c, tag)
                    jobs = self.jobs(share) - self.per_level(low_b["production_methods"])[2] + self.per_level(pms)[2]
                    if jobs > self.t["max_jobs_share"] * share["population"]:
                        continue
                    ratio = self.per_level(pms)[1] / self.usage_of(c)
                    weight = mix[cand] / (swapped[cand] + 1)   # keep the mix's proportions
                    if ratio > low_ratio * 1.25 and (best is None or weight > best[0]):
                        best = (weight, sid, share, low_b, c, pms, cand)
            if not best:
                return
            _, sid, share, low_b, c, pms, cand = best
            swapped[cand] += 1
            low_b["level"] -= 1
            share["buildings"] = [x for x in share["buildings"] if x["level"] > 0]
            cur = self.find(share, c)
            if cur:
                cur["level"] += 1
            else:
                share["buildings"].append({"type": c, "level": 1, "production_methods": pms})
            self.log["value_swaps"] += 1

    def market_of(self) -> dict:
        ov = self.W["overlords"]

        def top(t):
            seen = set()
            while t in ov and t not in seen:
                seen.add(t)
                t = ov[t]
            return t
        return {t: top(t) for t in self.W["countries"]}

    def close_markets(self, rounds: int = 6):
        market = self.market_of()
        for _ in range(rounds):
            res = B0.measure(self.W, self.rules)
            changed = False
            for m, mk in res["markets"].items():
                members = [t for t in self.group if market.get(t) == m]
                if not members:
                    continue
                members.sort(key=lambda t: (t != m, -self.W["countries"][t]["population"]))
                goods = sorted(mk["goods"].items(), key=lambda kv: kv[0] not in self.t["consumer_goods"])
                world = {}
                for other in res["markets"].values():
                    for g2, x2 in other["goods"].items():
                        w = world.setdefault(g2, [0.0, 0.0])
                        w[0] += x2["supply"]
                        w[1] += x2["industry"] + x2["military"] + x2["pops"]
                for g, x in goods:
                    demand = x["industry"] + x["military"] + x["pops"]
                    short = world.get(g, [0, 1])[0] < self.t["world_short"] * world.get(g, [0, 1])[1]
                    ceiling = self.t["export_ceiling"] if short else self.t["consumer_ceiling"]
                    if g in self.t["consumer_goods"] and demand > 1 and x["supply"] > ceiling * demand:
                        excess = x["supply"] - ceiling * demand
                        rows = [(b, share) for tag in members for sid, share in self.shares(tag) for b in share["buildings"]
                                if b["type"] not in PROTECTED and self.per_level(b["production_methods"])[0][("output", g)] > 0]
                        rows.sort(key=lambda r: -r[0]["level"])
                        owner = {id(b): tag for tag in members for sid, share in self.shares(tag) for b in share["buildings"]}
                        for b, share in rows:
                            out = self.per_level(b["production_methods"])[0][("output", g)]
                            cut = self.cuttable(owner[id(b)], b["type"], min(b["level"], int(excess // out)))
                            if cut <= 0:
                                continue
                            b["level"] -= cut
                            excess -= cut * out
                            changed = True
                            self.log[f"glut_{g}"] += cut
                        for tag in members:
                            for sid, share in self.shares(tag):
                                share["buildings"] = [b for b in share["buildings"] if b["level"] > 0]
                    surplus = world.get(g, [0, 1])[0] > self.t["world_surplus"] * world.get(g, [0, 1])[1]
                    if g in self.t["producers"] and g not in self.t["consumer_goods"] and surplus and demand > 1 \
                            and x["supply"] > self.t["input_ceiling"] * demand:
                        excess = x["supply"] - self.t["input_ceiling"] * demand
                        owner = {id(b): tag for tag in members for sid, share in self.shares(tag) for b in share["buildings"]}
                        exporters = set(self.t["protagonists"]) | set(self.t.get("floor_countries", []))
                        rows = [(b, share) for tag in members if tag not in exporters
                                for sid, share in self.shares(tag) for b in share["buildings"]
                                if b["type"] not in PROTECTED and self.main_output(b["production_methods"]) == g]
                        rows.sort(key=lambda r: -r[0]["level"])
                        for b, share in rows:
                            out = self.per_level(b["production_methods"])[0][("output", g)]
                            cut = self.cuttable(owner[id(b)], b["type"], min(b["level"], int(excess // out)))
                            if cut > 0:
                                b["level"] -= cut
                                excess -= cut * out
                                changed = True
                                self.log[f"input_glut_{g}"] += cut
                        for tag in members:
                            for sid, share in self.shares(tag):
                                share["buildings"] = [b for b in share["buildings"] if b["level"] > 0]
                    floor = self.t["input_floor_by_good"].get(g, self.t["input_floor"])
                    if g in self.t["producers"] and demand > 1 and x["supply"] < floor * demand:
                        need = floor * demand - x["supply"]
                        rooms = 0
                        for tag in members:
                            for b in self.t["producers"][g]:
                                while need > 0:
                                    probe = b if b != "staple" else "building_wheat_farm"
                                    out = self.per_level(self.choose(probe, tag))[0][("output", g)] or \
                                        (20 if b == "staple" else 0)
                                    # a level only where at least half of its output is needed (no glut in small markets),
                                    # except the first one of a good nobody makes there (a missing input costs 75%)
                                    first = x["supply"] <= 0 and need == floor * demand - x["supply"]
                                    if out < self.t.get("min_output_per_level", {}).get(g, 1e-9) or \
                                            (need < 0.5 * out and not first):
                                        break
                                    if not self.add_level(tag, b) and not (
                                            rooms < 400 and self.make_room(tag, b, mk["goods"]) and self.add_level(tag, b)):
                                        break
                                    rooms += 1
                                    need -= out
                                    changed = True
                                    self.log[f"closure_{g}"] += 1
            if not changed:
                break

    def set_total(self, tag: str, building: str, total: int, states: list | None = None, per_state_max: int = 10 ** 6):
        shares = dict(self.shares(tag))
        current = sum(b["level"] for s in shares.values() for b in s["buildings"] if b["type"] == building)
        if current > total:  # remove from the smallest-population shares first
            excess = current - total
            for sid in sorted(shares, key=lambda s: shares[s]["population"]):
                b = self.find(shares[sid], building)
                if b and excess > 0:
                    cut = min(b["level"], excess)
                    b["level"] -= cut
                    excess -= cut
                shares[sid]["buildings"] = [x for x in shares[sid]["buildings"] if x["level"] > 0]
            return
        order = states or sorted(shares, key=lambda s: (s != self.capital.get(tag), -shares[s]["population"]))
        order = [s for s in order if s in shares]
        need = total - current
        while need > 0:
            progress = False
            for sid in order:
                if need <= 0:
                    break
                share = shares[sid]
                b = self.find(share, building)
                if (b["level"] if b else 0) >= per_state_max or not self.building_ok(building, tag, sid):
                    continue
                weight = share["population"] / max(1, sum(shares[s]["population"] for s in order))
                if b and b["level"] >= max(1, math.ceil(total * max(weight, 0.4 if sid == self.capital.get(tag) else 0))) \
                        and any((self.find(shares[s], building) or {"level": 0})["level"] < per_state_max for s in order if s != sid):
                    continue
                if b:
                    b["level"] += 1
                else:
                    share["buildings"].append({"type": building, "level": 1, "production_methods": self.choose(building, tag)})
                need -= 1
                progress = True
            if not progress:
                break

    def state_buildings(self):
        for tag, n in self.t["railways"].items():   # minimums; fit_infrastructure adds lines where short
            if tag in self.group and self.total(tag, "building_railway") < n:
                self.set_total(tag, "building_railway", n, self.t["railway_states"].get(tag))
        for tag, n in self.t["universities"].items():
            if tag in self.group:
                self.set_total(tag, "building_university", n)
        for tag, points in self.t["construction_points"].items():
            if tag in self.group:
                per = self.rules.pm[self.choose("building_construction_sector", tag)[0]]["country"].get("country_construction_add", 2)
                self.set_total(tag, "building_construction_sector", math.ceil(points / per),
                               per_state_max=self.t["max_construction_sector_per_state"])
        # a port in every coastal in-scope country
        for tag in self.group:
            shares = dict(self.shares(tag))
            coastal = [s for s in shares if s in self.rules.coastal]
            if coastal and not any(self.find(shares[s], "building_port") for s in shares):
                self.add_level(tag, "building_port", 1, sorted(coastal, key=lambda s: -shares[s]["population"]))
                self.log["ports_added"] += 1
        # bureaucracy: 100 + admin output vs 10 per state + 4 per 100k people (x0.75 under reducing laws) + 1 per
        # government-owned level (the B0 rule)
        for tag in self.group:
            margin = self.t["bureaucracy_margin"]["advanced" if self.group[tag] in self.t["advanced_groups"] else "default"]
            reduce = 0.75 if B0.REDUCE_BUR & set(self.W["countries"][tag]["laws"]) else 1.0
            shares = dict(self.shares(tag))
            if not shares:
                continue
            base = sum(10 + 4 * s["population"] / 100000 * reduce for s in shares.values())

            def balance():
                supply, gov = 100.0, 0
                for s in shares.values():
                    for b in s["buildings"]:
                        if self.rules.building.get(b["type"], {}).get("gov"):
                            gov += b["level"]
                        for pm in b["production_methods"]:
                            supply += self.rules.pm.get(pm, {"country": {}})["country"].get("country_bureaucracy_add", 0) * b["level"]
                return supply, base + gov
            for _ in range(2000):
                supply, cost = balance()
                if supply >= margin * cost:
                    break
                sid = max((s for s in shares if self.building_ok("building_government_administration", tag, s)),
                          key=lambda s: shares[s]["population"] / (1 + (self.find(shares[s], "building_government_administration") or {"level": 0})["level"]),
                          default=None)
                if sid is None:
                    break
                b = self.find(shares[sid], "building_government_administration")
                if b:
                    b["level"] += 1
                else:
                    shares[sid]["buildings"].append({"type": "building_government_administration", "level": 1,
                                                     "production_methods": self.choose("building_government_administration", tag)})
                self.log["gov_admin_added"] += 1

    def diff(self) -> dict:
        out = {}
        for sid, st in self.W["states"].items():
            for tag, share in st["owners"].items():
                if tag not in self.group:
                    continue
                before = {b["type"]: b for b in self.report["states"][sid]["owners"][tag].get("buildings", [])}
                after = {b["type"]: b for b in share["buildings"]}
                rows = {}
                for bt in sorted(set(before) | set(after)):
                    a, b = before.get(bt), after.get(bt)
                    need = set(self.data["buildings"].get(bt, {}).get("unlocking_technologies", []))
                    if b is not None and not need <= set(self.W["countries"][tag]["technologies"]):
                        b = None  # an inherited building the owner cannot have (Lourenço Marques' port)
                        self.log["invalid_removed"] += 1
                    if b is None:
                        rows[bt] = 0
                    elif a is None or a["level"] != b["level"] or a["production_methods"] != b["production_methods"]:
                        # an explicit entry is validated by Atlas: keep valid methods, replace invalid inherited ones
                        pms = self.choose(bt, tag, b["production_methods"])
                        if pms != b["production_methods"]:
                            self.log["inherited_methods_fixed"] += 1
                        rows[bt] = {"level": b["level"], "production_methods": pms}
                if rows:
                    out.setdefault(sid, {})[tag] = rows
        return out


def main() -> None:
    p = Planner()
    before = B0.measure(p.W, p.rules)
    p.upgrade_methods()
    p.ensure_canon()
    p.fit_value_added()
    p.close_markets()
    p.state_buildings()
    p.close_markets()
    p.fit_infrastructure()
    p.fit_value_added()   # closure may overshoot and the infrastructure cut undershoot a target: fit again
    p.close_markets(3)
    p.close_world()
    p.connect_isolated()
    p.naval_administration()
    p.fit_infrastructure()
    p.close_markets(2)     # railways need engines and coal, ports clippers
    p.fit_infrastructure()
    after = B0.measure(p.W, p.rules)
    countries = {}
    for tag in sorted(p.group):
        b, a = before["countries"].get(tag, {}), after["countries"].get(tag, {})
        pop = p.W["countries"][tag]["population"]
        countries[tag] = {"group": p.group[tag], "population": pop,
                          "va_target": round(p.target(tag)), "va_before": round(b.get("va", 0)), "va_after": round(a.get("va", 0)),
                          "levels_before": b.get("levels", 0), "levels_after": a.get("levels", 0),
                          "bureaucracy": [round(a.get("bureaucracy", 0)), round(a.get("bur_cost", 0))],
                          "innovation": round(a.get("innovation", 0)), "construction": round(a.get("construction", 0))}
    summary = {"countries": len(p.group), **dict(p.log),
               "levels_before": sum(c["levels"] for c in before["countries"].values()),
               "levels_after": sum(c["levels"] for c in after["countries"].values()),
               "va_before": round(sum(c["va"] for c in before["countries"].values())),
               "va_after": round(sum(c["va"] for c in after["countries"].values()))}
    out = {"summary": summary, "countries": countries, "industry": p.diff()}
    (HERE / "plan.yml").write_text(HEADER + yaml.safe_dump(out, allow_unicode=True, sort_keys=False, width=120))
    top = sorted(countries.items(), key=lambda x: -x[1]["va_after"])[:12]
    print(f"wrote plan.yml: {summary}")
    for tag, c in top:
        print(f"  {tag} VA {c['va_before']} -> {c['va_after']} (target {c['va_target']}) levels {c['levels_before']} -> {c['levels_after']} BUR {c['bureaucracy']} innov {c['innovation']} constr {c['construction']}")


if __name__ == "__main__":
    main()
