"""D5: replace the custom ve_* subject types with the game's vanilla types (user decision 25 Sep 2026).

The fourteen custom types were confusing; the user will specify new ones later. Every subject
relation keeps its overlord, subject and liberty desire and gets the vanilla type that matches its
old base and the vanilla country-type rules:

- tight bonds (old vassal base) -> `puppet` under a recognized overlord, `vassal` under an
  unrecognized one (vanilla vassal/tributary accept only unrecognized overlords);
- loose bonds (old protectorate/tributary base) -> `protectorate` / `tributary` in the same way;
- colonial charters -> `colony` (New Andalusia, the canon's "broad autonomous charter": `dominion`);
  vanilla colony/dominion need a `colonial` subject, so these colonies become country type `colonial`;
- the London crown's overseas dependencies -> `crown_land`;
- crown unions -> `personal_union`.
Writes plan.yml (generated; review, do not hand-edit).
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
TIGHT = {"ve_shah_vassal", "ve_feudal_vassal", "ve_autonomous_compact", "ve_contractual_vassal", "ve_nile_compact",
         "ve_emirate_compact", "ve_japanese_domain"}
LOOSE = {"ve_limited_protection", "ve_hajj_protection", "ve_tributary_compact", "ve_tatar_tribute", "ve_mandala_autonomy"}
DOMINION = {"VNE"}
CROWN_LAND = {"GBR"}


def main() -> None:
    world = yaml.safe_load((ROOT / "world/scenario.yml").read_text())
    index = json.loads((ROOT / "build/index.json").read_text())
    kind = lambda tag: world["countries"].get(tag, {}).get("country_type") or index["countries"][tag]["country_type"]
    subjects, colonial = [], {}
    for row in world["diplomacy"]["subjects"]:
        old, over, sub = row["type"], row["overlord"], row["subject"]
        unrecognized = kind(over) == "unrecognized"
        if old == "ve_colonial_charter":
            if sub in CROWN_LAND:
                new = "crown_land"
            else:
                new = "dominion" if sub in DOMINION else "colony"
                colonial[sub] = kind(sub)
        elif old == "ve_crown_union":
            new = "personal_union"
        elif old in TIGHT:
            new = "vassal" if unrecognized else "puppet"
        elif old in LOOSE:
            new = "tributary" if unrecognized else "protectorate"
        else:
            raise ValueError(f"{over}>{sub}: unmapped type {old}")
        subjects.append({"overlord": over, "subject": sub, "from": old, "to": new})
    (HERE / "plan.yml").write_text(
        "# Generated by plan.py from the active world; review, do not hand-edit.\n" +
        yaml.safe_dump({"version": 1, "subjects": subjects,
                        "colonial": {tag: {"from": before, "to": "colonial"} for tag, before in sorted(colonial.items())}},
                       allow_unicode=True, sort_keys=False, width=110))
    counts = {}
    for row in subjects:
        counts[row["to"]] = counts.get(row["to"], 0) + 1
    print(f"{len(subjects)} subjects -> {counts}; colonial country type for {len(colonial)}: {' '.join(sorted(colonial))}")


if __name__ == "__main__":
    main()
