"""M4: write the commanders and formation names of plan.yml as mod files (outside Atlas).

Outputs (generated; do not hand-edit):
- common/history/characters/ve_m4_commanders.txt: one general per army and one admiral per
  fleet, less those the tag's vanilla history already creates. Names, portrait, traits and interest
  group come from the game's defaults for the country's primary culture; `hq` places the commander
  in the formation's strategic region (the vanilla pattern for GBR's admirals).
- localization/<language>/ve_m4_military_l_<language>.yml: the formation names (ve_m4_* keys).
Every country must be landed and organized in the active report. Run after `atlas build` and the
active report.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
NOTE = "# Generated by scenarios/atlas/mechanics_m4_military/build.py from plan.yml; do not hand-edit.\n"
RANKS = {1, 2, 3, 4, 5}


def write(rel: str, text: str) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + text, encoding="utf-8")


def main() -> None:
    plan = yaml.safe_load((HERE / "plan.yml").read_text())
    report = json.loads((ROOT / "build/world-political/active-political-report.json").read_text())
    regions = json.loads((ROOT / "build/m4-strategic-regions.json").read_text())["entries"]
    errors, blocks, counts = [], [], {"general": 0, "admiral": 0}
    for tag, row in sorted(plan["countries"].items()):
        if tag not in report["countries"]:
            errors.append(f"{tag}: not landed")
            continue
        owned = {s for s, st in report["states"].items() if tag in st["owners"]}
        items = []
        for c in row["commanders"]:
            if c["rank"] not in RANKS or c["hq"] not in regions or not owned & set(regions[c["hq"]]["states"]):
                errors.append(f"{tag}: commander {c} has no valid rank or owned headquarters region")
                continue
            items.append(f"\t\tcreate_character = {{\n\t\t\tis_{c['role']} = yes\n\t\t\tculture = primary_culture\n"
                         f"\t\t\thq = {c['hq']}\n\t\t\tcommander_rank = commander_rank_{c['rank']}\n\t\t}}")
            counts[c["role"]] += 1
        if items:
            blocks.append(f"\tc:{tag} ?= {{\n" + "\n".join(items) + "\n\t}")
    names = plan["names"]
    used = {f["name"] for row in plan["countries"].values() for f in row["formations"]}
    if used - set(names):
        errors.append(f"formations without a name: {sorted(used - set(names))[:5]}")
    if errors:
        raise SystemExit("\n".join(errors[:40]))
    write("common/history/characters/ve_m4_commanders.txt", NOTE + "CHARACTERS = {\n" + "\n".join(blocks) + "\n}\n")
    for language, key in (("english", "en"), ("turkish", "tr")):
        rows = "".join(f' {k}:0 "{v[key]}"\n' for k, v in sorted(names.items()) if k in used)
        write(f"localization/{language}/ve_m4_military_l_{language}.yml", f"l_{language}:\n" + NOTE.replace("#", " #", 1) + rows)
    print(f"wrote commanders for {len(blocks)} countries ({counts['general']} generals, {counts['admiral']} admirals) "
          f"and {len(used)} formation names")


if __name__ == "__main__":
    main()
