"""M1b: education plan for Islamic countries that keep their vanilla starting history.

The 159 M1 countries get their schools from mechanics_m1_institutions/classify.py (run with
--targets). The remaining non-decentralized Islamic countries still start from vanilla
`effect_starting_politics_*` effects, which give no schools and, for `traditional`, serfdom.
They get, merged on top of the vanilla laws:
- religious schools (Egypt, Islamic core: public schools), levels by the same rule as M1 (1-2);
- tenant farmers where the land law is serfdom or left to the vanilla effect (both school laws
  disallow serfdom); every other land law is kept;
- rationalism / empiricism when the vanilla technology tier lacks them.
Non-Islamic vanilla countries keep their vanilla education; only their starting literacy input
changes (prepare.py).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(HERE.parent / "mechanics_m1_institutions"))
from classify import islamic_schools  # noqa: E402

LAND_KEPT = {"law_tenant_farmers", "law_commercialized_agriculture", "law_homesteading", "law_collectivized_agriculture",
             "law_peasant_proprietorship", "law_latifundias"}


def main() -> None:
    world = yaml.safe_load((ROOT / "build/mechanics/m1b-source.yml").read_text())
    report = json.loads((ROOT / "build/mechanics/m1b-source-report.json").read_text())
    rules = json.loads((HERE.parent / "mechanics_m1_institutions/law-rules.json").read_text())
    targets = yaml.safe_load((HERE / "targets.yml").read_text())["countries"]
    m1 = yaml.safe_load((HERE.parent / "mechanics_m1_institutions/plan.yml").read_text())["countries"]
    text = (ROOT / "common/history/countries/ve_scenario_countries.txt").read_text(encoding="utf-8-sig")
    blocks = dict(re.findall(r"\nc:(\w+) \?= \{(.*?)\n\}", text, re.S))
    plan = {}
    for tag, goal in sorted(targets.items()):
        if tag in m1 or not goal["band"].startswith("islam") or goal["type"] == "decentralized":
            continue
        reported = set(report["countries"][tag]["laws"])
        techs = set(report["countries"][tag]["technologies"])
        edu = "law_public_schools" if goal["band"] in ("islam_lead", "islam_core") else "law_religious_schools"
        laws = [edu]
        land = [law for law in reported if rules[law]["group"] == "lawgroup_land_reform"]
        if not land or land[0] not in LAND_KEPT:
            laws.append("law_tenant_farmers")
        church = [law for law in reported if rules[law]["group"] == "lawgroup_church_and_state"]
        if church and set(rules[edu]["disallowing"]) & set(church):
            laws.append("law_people_of_the_book")
        add = sorted(set(rules[edu]["techs"]) - techs)
        existing = (world["countries"].get(tag, {}).get("laws") or {}).get("values", [])
        plan[tag] = {
            "band": goal["band"], "target": goal["target"],
            "politics_effect": sorted(set(re.findall(r"effect_starting_politics_\w+", blocks.get(tag, "")))),
            "add_technologies": add, "laws": sorted(set(existing) | set(laws)), "new_laws": sorted(laws),
            "institutions": {"institution_schools": islamic_schools(goal["target"], goal["band"])},
        }
    (HERE / "plan.yml").write_text(
        "# Generated by plan.py from targets.yml and the vanilla history of each country; do not hand-edit.\n" +
        yaml.safe_dump({"version": 1, "countries": plan}, allow_unicode=True, sort_keys=True, width=110))
    print(f"planned {len(plan)} vanilla-history Islamic countries; tenant farmers "
          f"{sum('law_tenant_farmers' in r['new_laws'] for r in plan.values())}; tech adds "
          f"{sum(bool(r['add_technologies']) for r in plan.values())}")


if __name__ == "__main__":
    main()
